# This file assume app is installed at/run from /opt/hyyperwan
# if it is not, then ExecStart path should be adjusted accordingly

[Unit]
Description=HyyperWAN Network Condition Control Application (HTTP)
After=network.target

[Service]
# Run as root because tc qdisc commands require root privileges
User=root
Group=root
WorkingDirectory=/opt/hyyperwan
ExecStart=/usr/bin/python3 /opt/hyyperwan/app.py
Environment="FLASK_APP=app.py"
Environment="FLASK_RUN_HOST=0.0.0.0"
Environment="FLASK_RUN_PORT=8080"
# HTTP configuration
Environment="USE_HTTPS=false"
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target